package com.xhgjky.bean;
// Generated 2018-6-27 10:36:16 by Hibernate Tools 3.2.2.GA

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private String orderId;
	private String orderName;

	public Order() {
	}

	public Order(String orderId) {
		this.orderId = orderId;
	}

	public Order(String orderId, String orderName) {
		this.orderId = orderId;
		this.orderName = orderName;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getOrderName() {
		return this.orderName;
	}

	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

}
